### ISSUE TITLE
Feature: 마커 클릭시 해당 데이터 로드하여 렌더링

### ISSUE THREAD

**Issue by joshyeom** [my-neighborhood-solver/frontend#128]
## Description
마커를 클릭하면 해당 의뢰 정보가 박스에 나오고 해당 박스를 클릭하면 viewPage로 이동

## To-Do
- [x] 마커 박스 생성
- [x] 마커 박스 스타일링
- [x] 마커 데이터 로드
- [x] 박스 닫기 버튼 활성화
- [x] 박스 클릭시 viepPage로 이동
