### ISSUE TITLE
Feature: 카카오 소셜 로그인 성공할 때 활성화 시킬 아이콘 & 버튼

### ISSUE THREAD

**Issue by zerosubin** [my-neighborhood-solver/frontend#49]
## Description
카카오 소셜 로그인는 구현했지만 여전히 헤더에는 로그인 버튼이 보여진다. 따라서, 헤더 페이지에 사용자 정보를 받아와서 로그인 버튼 대신에 알람 아이콘이 보여지도록 구현할 것이다. 또한 마이페이지에 로그아웃 버튼, 탈퇴하기 버튼을 추가해서 카카오 소셜의 로그아웃 & 탈퇴하기 기능을 구현할 예정이다.

## To-Do
- [x] 헤더 알림 아이콘
- [x] 로그아웃 버튼 + 기능
- [x] 탈퇴하기 버튼 + 기능

## ETC
이 기능을 구현한다면 의뢰 글처럼 로그인한 사람에게만 제공되는 페이지를 따로 구별해 로그인 여부를 판별하여 로그인 하지 않은 사용자에겐 로그인을 해달라는 모달창을 만들 것이고, 만약 로그인을 했다면 페이지 이동이 가능하도록 구현할 것이다.
